// Generated by KLFC 1.5.7
// https://github.com/39aldo39/klfc

#include "unimap_trans.h"
#include "action_util.h"
#include "action_layer.h"

enum function_id {
    F_MODIFIER,
};

enum modifier_id {
    MOD_EXTEND,
};

#define AC_FN0 ACTION_FUNCTION_OPT(F_MODIFIER, MOD_EXTEND)
#define AC_FN1 ACTION_MODS_KEY(MOD_BIT(KC_LCTL), KC_Z)
#define AC_FN2 ACTION_MODS_KEY(MOD_BIT(KC_LCTL), KC_X)
#define AC_FN3 ACTION_MODS_KEY(MOD_BIT(KC_LCTL), KC_C)
#define AC_FN4 ACTION_MODS_KEY(MOD_BIT(KC_LCTL), KC_V)

#ifdef KEYMAP_SECTION_ENABLE
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] __attribute__ ((section (".keymap.keymaps"))) = {
#else
const action_t actionmaps[][UNIMAP_ROWS][UNIMAP_COLS] PROGMEM = {
#endif
    // None
    [0] = UNIMAP(
               F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,
     ESC,       F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9, F10, F11, F12,          PSCR,SLCK,PAUS,         VOLD,VOLU,MUTE,
    QUOT,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0,MINS, EQL,JYEN,BSPC,      INS,HOME,PGUP,    NLCK,PSLS,PAST,PMNS,
     TAB,   Q,   D,   R,   W,   B,   J,   F,   U,   P,  NO,  NO,LBRC,     RBRC,      DEL, END,PGDN,      P7,  P8,  P9,PPLS,
     FN0,   A,   S,   H,   T,   G,   Y,   N,   E,   O,   I,  NO,     NUHS, ENT,                          P4,  P5,  P6,PCMM,
    LSFT,BSLS,   Z,   X,   M,   C,   V,   K,   L,COMM, DOT,SCLN,     SLSH,RSFT,            UP,           P1,  P2,  P3,PENT,
    LCTL,LGUI,LALT,MHEN,           SPC,          HENK,KANA,RALT,RGUI, APP,RCTL,     LEFT,DOWN,RGHT,      P0,     PDOT,PEQL
    ),
    // Extend
    [1] = UNIMAP(
              TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,
    TRNS,     MPRV,MPLY,MNXT,MUTE,VOLD,VOLU,TRNS,TRNS,WHOM,MYCM,MSEL,CALC,          TRNS,TRNS,TRNS,         TRNS,TRNS,TRNS,
    CAPS,  F1,  F2,  F3,  F4,  F5,  F6,  F7,  F8,  F9, F10, F11, F12,TRNS, PWR,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS, ESC,WBAK,WREF,WFWD,TRNS,PGUP,HOME,  UP, END,PGUP, ESC, INS,     SLEP,     TRNS,TRNS,TRNS,    TRNS,TRNS,TRNS,TRNS,
    TRNS,LALT,LSFT,LCTL,QUOT,TRNS,PGDN,LEFT,DOWN,RGHT,PGDN, APP,     TRNS,TRNS,                        TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS, FN1, FN2, FN3, FN4,TRNS, ENT,BSPC, DEL,PSCR,TRNS,     TRNS,TRNS,          TRNS,         TRNS,TRNS,TRNS,TRNS,
    TRNS,TRNS,TRNS,TRNS,           ENT,          TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,     TRNS,TRNS,TRNS,    TRNS,     TRNS,TRNS
    ),
};

enum vmod_mask {
    VMOD_EXTEND_MASK = 1,
};

uint8_t vmods = 0;

const uint8_t layer_states[] = {
    0x1, // None
    0x3, // Extend
};

void action_function(keyrecord_t *record, uint8_t id, uint8_t opt) {
    uint8_t pressed = record->event.pressed;
    switch (id) {
        case F_MODIFIER:
            // Set the new modifier
            switch (opt) {
                case MOD_EXTEND: pressed ? (vmods |= VMOD_EXTEND_MASK) : (vmods &= ~VMOD_EXTEND_MASK); break;
            }

            // Update the layer
            uint8_t mods = get_mods();
            uint8_t layer_index = 0;
            layer_index |= vmods << 0;
            layer_clear();
            layer_or(layer_states[layer_index]);
            break;
    }
}
